// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Regenerate: curl -s https://dash.cloudflare.com/assets/cf-common.<hash>.js and extract the
//   /"api_tokens\.permission_([a-z0-9_]+)"\s*:\s*`([^`]*)`/ pairs. These are Cloudflare's own
//   token-template permission keys (the ?permissionGroupKeys= URL format), read from the dashboard
//   bundle: the API never exposes them and they are NOT derivable from group names
//   (containers != workers_containers, workers_r2 != workers_r2_storage, browser_rendering =
//   "Browser Run"). A recipe may only declare keys in this table, so nothing outside this ceiling
//   can be requested. `danger` marks escalation / account-governance / financial permissions a
//   normal app should never need — the wizard warns when one is declared.

export interface CfTokenPermission {
  name: string;
  danger?: boolean;
}

export const CF_TOKEN_PERMISSIONS: Record<string, CfTokenPermission> = {
  access: { name: "Access: Apps and Policies" },
  access_acct: { name: "Access: Organizations, Identity Providers, and Groups", danger: true },
  access_app: { name: "Access: Apps" },
  access_audit_log: { name: "Access: Audit Logs" },
  access_certificate: { name: "Access: Mutual TLS Certificates" },
  access_custom_page: { name: "Access: Custom Pages" },
  access_device_posture: { name: "Access: Device Posture" },
  access_group: { name: "Access: Groups" },
  access_idp: { name: "Access: Identity Providers", danger: true },
  access_key: { name: "Access: Keys" },
  access_org: { name: "Access: Organizations", danger: true },
  access_policy: { name: "Access: Policies" },
  access_policy_test: { name: "Access: Policy Test" },
  access_population: { name: "Access: Populations" },
  access_saml_certificate: { name: "Access: SAML Certificate" },
  access_scim_log: { name: "Access: SCIM Logs" },
  access_seats: { name: "Zero Trust: Seats", danger: true },
  access_ssh_auditing: { name: "Access: SSH Auditing" },
  access_tag: { name: "Access: Tags" },
  access_users: { name: "Access: Users" },
  account_abuse_protection_pii: { name: "Account Abuse Protection PII" },
  account_analytics: { name: "Account Analytics" },
  account_api_tokens: { name: "API Tokens", danger: true },
  account_custom_asset: { name: "Account Custom Assets" },
  account_custom_error_rules: { name: "Account Custom Error Rules" },
  account_custom_pages: { name: "Account Custom Pages" },
  account_disable_esc: { name: "Disable ESC" },
  account_firewall_access_rules: { name: "Account Firewall Access Rules" },
  account_rule_lists: { name: "Account Filter Lists" },
  account_rule_policies: { name: "Rule Policies" },
  account_rulesets: { name: "Account Rulesets" },
  account_security_center_insights: { name: "Account Security Center Insights" },
  account_settings: { name: "Account Settings" },
  account_ssl_and_certificates: { name: "Account: SSL and Certificates" },
  account_waf: { name: "Account WAF" },
  account_waiting_rooms: { name: "Account Waiting Room" },
  address_maps: { name: "Address Maps" },
  agentmemory: { name: "Agent Memory" },
  ai: { name: "Workers AI" },
  ai_search: { name: "AI Search" },
  aiaudit: { name: "AI Crawl Control" },
  aig: { name: "AI Gateway" },
  analytics: { name: "Analytics" },
  api_gateway: { name: "API Gateway" },
  api_tokens: { name: "API Tokens", danger: true },
  apps: { name: "Apps" },
  argotunnel: { name: "Cloudflare Tunnel" },
  artifacts: { name: "Artifacts" },
  audit_logs: { name: "Audit Logs" },
  billing: { name: "Billing", danger: true },
  bot_management: { name: "Bot Management" },
  bot_management_feedback: { name: "Bot Management Feedback" },
  browser_rendering: { name: "Browser Run" },
  cache: { name: "Cache Purge" },
  cache_settings: { name: "Cache Rules" },
  calls: { name: "Cloudflare Calls" },
  casb: { name: "Cloudflare CASB" },
  challenge_widgets: { name: "Turnstile" },
  chinanetwork_steering: { name: "China Network Steering" },
  cloud_connector: { name: "Cloud Connector" },
  cloud_email_security: { name: "Email Security" },
  cloudchamber: { name: "Cloudchamber" },
  cloudforce_one: { name: "Cloudforce One" },
  config_settings: { name: "Config Rules" },
  connectivity_directory: { name: "Connectivity Directory" },
  connectivity_directory_admin: { name: "Connectivity Directory Admin" },
  connectivity_directory_bind: { name: "Connectivity Directory Bind" },
  constellation: { name: "Constellation" },
  containers: { name: "Containers" },
  custom_errors: { name: "Custom Error Rules" },
  custom_pages: { name: "Custom Pages" },
  d1: { name: "D1" },
  d1_content: { name: "D1 Content" },
  ddos_botnet_feed: { name: "DDoS Botnet Feed" },
  ddos_protection: { name: "DDoS Protection" },
  dex: { name: "Cloudflare DEX" },
  dls: { name: "Data Localization Suite" },
  dns: { name: "DNS" },
  dns_firewall: { name: "DNS Firewall" },
  dns_settings: { name: "DNS Settings" },
  dns_view: { name: "DNS Views" },
  dynamic_redirect: { name: "Single Redirect" },
  email_routing_address: { name: "Email Routing Addresses" },
  email_routing_rule: { name: "Email Routing Rules" },
  email_security_dmarcreports: { name: "Dmarc Management" },
  email_sending: { name: "Email Sending" },
  error: { name: "Choose a permission" },
  fbm: { name: "Network flow" },
  field_extractor: { name: "Field Extractors" },
  firewall_for_ai: { name: "AI Security for Apps" },
  firewall_services: { name: "Firewall Services" },
  flagship: { name: "Flagship" },
  fraud_detection: { name: "Fraud Detection" },
  fraud_events: { name: "Fraud Events API" },
  fraud_feedback: { name: "Fraud Feedback API" },
  healthcheck: { name: "Health Checks" },
  http_applications: { name: "HTTP Applications" },
  http_ddos_managed_ruleset: { name: "HTTP DDoS Managed Ruleset" },
  images: { name: "Cloudflare Images" },
  intel: { name: "Intel" },
  iot: { name: "IOT" },
  ip_prefix: { name: "IP Prefixes" },
  ip_prefix_bgp_on_demand: { name: "IP Prefixes: BGP On Demand" },
  l4_ddos_managed_ruleset: { name: "L3/4 DDoS Managed Ruleset" },
  load_balancers: { name: "Load Balancers" },
  load_balancers_account: { name: "Load Balancing: Account Load Balancers" },
  load_balancing_monitors_and_pools: { name: "Load Balancing: Monitors And Pools" },
  logs: { name: "Logs" },
  magic_firewall: { name: "Firewall policy" },
  magic_transit: { name: "Magic Transit" },
  magic_wan: { name: "Cloudflare WAN" },
  managed_headers: { name: "Managed Headers" },
  mass_url_redirects: { name: "Bulk URL Redirects" },
  mcp_portals: { name: "MCP Portals" },
  member: { name: "Invites", danger: true },
  memberships: { name: "Memberships", danger: true },
  multi_user: { name: "Users", danger: true },
  notifications: { name: "Notifications" },
  oauth_client: { name: "OAuth Clients", danger: true },
  origin: { name: "Origin Rules" },
  page: { name: "Cloudflare Pages" },
  page_rules: { name: "Page Rules" },
  page_shield: { name: "Client-side security" },
  pcaps_api: { name: "Firewall Policy Packet Captures" },
  pipelines: { name: "Workers Pipelines" },
  pubsub: { name: "Pub/Sub" },
  query_cache: { name: "Hyperdrive" },
  queues: { name: "Queues" },
  r2_bucket_selected: { name: "R2 bucket scoped token can only be managed by R2 token UI" },
  r2_catalog: { name: "Workers R2 Data Catalog" },
  r2_catalog_sql: { name: "Workers R2 SQL" },
  radar: { name: "Radar" },
  realtime: { name: "Realtime" },
  realtime_admin: { name: "Realtime Admin" },
  registrar_domains: { name: "Registrar: Domains" },
  request_tracer: { name: "Allow Request Tracer" },
  response_compression: { name: "Response Compression" },
  sanitize: { name: "Sanitize" },
  scim_provisioning: { name: "SCIM Provisioning", danger: true },
  secrets_store: { name: "Secrets Store" },
  select_configuration: { name: "Select Configuration" },
  service_token: { name: "Access: Service Tokens", danger: true },
  snippets: { name: "Snippets" },
  ssl_and_certificates: { name: "SSL and Certificates" },
  sso_connector: { name: "SSO Connector", danger: true },
  stream: { name: "Stream" },
  subscriptions: { name: "Subscriptions", danger: true },
  teams: { name: "Zero Trust" },
  teams_cds_compute_account: { name: "Cloudflare CDS Compute Account" },
  teams_connector_cloudflared: { name: "Cloudflare One Connector: cloudflared" },
  teams_connector_warp: { name: "Cloudflare One Connector: WARP" },
  teams_connectors: { name: "Cloudflare One Connectors" },
  teams_networks: { name: "Cloudflare One Networks" },
  teams_pii: { name: "Zero Trust: PII" },
  teams_resilience: { name: "Zero Trust Resilience" },
  transform_rules: { name: "Transform Rules" },
  trust_and_safety: { name: "Trust and Safety" },
  url_scanner: { name: "URL Scanner" },
  user_details: { name: "User Details" },
  vectorize: { name: "Vectorize" },
  waiting_rooms: { name: "Waiting Room" },
  web3_hostnames: { name: "Web3 Hostnames" },
  workers: { name: "Workers" },
  workers_kv_storage: { name: "Workers KV Storage" },
  workers_observability: { name: "Workers Observability" },
  workers_observability_telemetry: { name: "Workers Observability Telemetry" },
  workers_r2: { name: "Workers R2 Storage" },
  workers_routes: { name: "Workers Routes" },
  workers_scripts: { name: "Workers Scripts" },
  workers_tail: { name: "Workers Tail" },
  zaraz: { name: "Zaraz" },
  zone: { name: "Zone" },
  zone_access: { name: "Access: Apps and Policies" },
  zone_custom_asset: { name: "Zone Custom Assets" },
  zone_disable_esc: { name: "Disable ESC" },
  zone_security_center_insights: { name: "Zone Security Center Insights" },
  zone_settings: { name: "Zone Settings" },
  zone_transform_rules: { name: "Transform Rules" },
  zone_versioning: { name: "Zone Versioning" },
  zone_waf: { name: "Zone WAF" },
};

export type CfTokenPermType = "read" | "edit";

export function isKnownTokenPermission(key: string): boolean {
  return Object.prototype.hasOwnProperty.call(CF_TOKEN_PERMISSIONS, key);
}
